// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth.go

export type AccountsAuthHandler = any;
export interface RequestMagicLinkRequest {
  email: string;
}
export interface RequestMagicLinkResponse {
  message: string;
}
export interface AuthenticateRequest {
  email: string;
  code: string;
}
export interface AuthenticateResponse {
  session_token: string;
  session_created_at: string;
  session_expires_at: string;
  is_new_user: boolean;
  session_info: SessionInfoResponse;
}

//////////
// source: handlers.go

export type AccountsHandler = 
    AccountsAuthHandler;

//////////
// source: responses.go

export interface OrganizationForSessionInfoResponse {
  organization_id: number /* int */;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  latitude: number /* float64 */;
  longitude: number /* float64 */;
  user_role: any /* accounts.Role */;
  user_permissions: any /* accounts.Permission */[];
}
export interface UserForSessionInfoResponse {
  id: number /* int */;
  name: string;
  email: string;
  phone: number /* int */;
  address: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  latitude: number /* float64 */;
  longitude: number /* float64 */;
}
export interface SessionInfoResponse {
  user: UserForSessionInfoResponse;
  organizations: OrganizationForSessionInfoResponse[];
  is_new_user: boolean;
}
