// Code generated by tygo. DO NOT EDIT.

//////////
// source: handlers.go

export type RidesHandler = any;
export interface CreateRideRequest {
  uuid: string;
  type: string;
  start_time: string;
  finish_time: string;
  geo_points: string;
  raw_coords?: string;
  freeroam: boolean;
  distance: number /* float64 */;
}
export interface CreateRideResponse {
  ride_uuid: string;
  distance_traveled: number /* float64 */;
  valid: boolean;
  raw_coords: string;
  geo_points: string;
  start_time: any /* time.Time */;
  finish_time: any /* time.Time */;
  freeroam: boolean;
  type: string;
  type_changed_from: string;
}
export interface RideResponse {
  ride_id: number /* int */;
  ride_uuid: string;
  user_id: number /* int */;
  distance_traveled: number /* float64 */;
  valid: boolean;
  raw_coords: string;
  geo_points: string;
  start_time: any /* time.Time */;
  finish_time: any /* time.Time */;
  freeroam: boolean;
  type: string;
  type_changed_from: string;
}
