// Code generated by tygo. DO NOT EDIT.

//////////
// source: handlers.go

export interface ScoresHandler {
}
export interface ScoreConfigForResponse {
  points_per_kg: number /* int */;
  rides_points_per_km_walking: number /* int */;
  rides_points_per_km_bicycle: number /* int */;
  valid_from: string;
  valid_to: string;
}
export type GetScoreConfigsResponse = ScoreConfigForResponse[];
export interface LeaderboardItemForLeaderboardResponse {
  user_id: number /* int */;
  score: number /* int */;
  rank: number /* int */;
  user_name: string;
}
export type GetLeaderboardResponse = LeaderboardItemForLeaderboardResponse[];
export interface GetMyScoreHistoryResponse {
  items: ScoreHistoryItemForResponse[];
  total_score: number /* int */;
  total_score_in_month: number /* int */;
}
export interface GetOrganizationScoresResponse {
  items: ScoreHistoryItemForResponse[];
}
export interface GetMyTotalScoreResponse {
  total_score: number /* int */;
}

//////////
// source: responses.go

export interface ScoreHistoryItemForResponse {
  user_id: number /* int */;
  title: string;
  is_valid: boolean;
  score: number /* float64 */;
  date: any /* time.Time */;
  score_type: string;
  score_metadata: string;
}
