// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
package database

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransientDatabase creates a new instance of MockTransientDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransientDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransientDatabase {
	mock := &MockTransientDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransientDatabase is an autogenerated mock type for the TransientDatabase type
type MockTransientDatabase struct {
	mock.Mock
}

type MockTransientDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransientDatabase) EXPECT() *MockTransientDatabase_Expecter {
	return &MockTransientDatabase_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransientDatabase_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTransientDatabase_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTransientDatabase_Expecter) Close() *MockTransientDatabase_Close_Call {
	return &MockTransientDatabase_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTransientDatabase_Close_Call) Run(run func()) *MockTransientDatabase_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransientDatabase_Close_Call) Return(err error) *MockTransientDatabase_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransientDatabase_Close_Call) RunAndReturn(run func() error) *MockTransientDatabase_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransientDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransientDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTransientDatabase_Expecter) Delete(ctx interface{}, key interface{}) *MockTransientDatabase_Delete_Call {
	return &MockTransientDatabase_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockTransientDatabase_Delete_Call) Run(run func(ctx context.Context, key string)) *MockTransientDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_Delete_Call) Return(err error) *MockTransientDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransientDatabase_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockTransientDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransientDatabase_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTransientDatabase_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTransientDatabase_Expecter) Exists(ctx interface{}, key interface{}) *MockTransientDatabase_Exists_Call {
	return &MockTransientDatabase_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockTransientDatabase_Exists_Call) Run(run func(ctx context.Context, key string)) *MockTransientDatabase_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_Exists_Call) Return(b bool, err error) *MockTransientDatabase_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTransientDatabase_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockTransientDatabase_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransientDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransientDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTransientDatabase_Expecter) Get(ctx interface{}, key interface{}) *MockTransientDatabase_Get_Call {
	return &MockTransientDatabase_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockTransientDatabase_Get_Call) Run(run func(ctx context.Context, key string)) *MockTransientDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_Get_Call) Return(s string, err error) *MockTransientDatabase_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTransientDatabase_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockTransientDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransientDatabase_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockTransientDatabase_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransientDatabase_Expecter) Ping(ctx interface{}) *MockTransientDatabase_Ping_Call {
	return &MockTransientDatabase_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockTransientDatabase_Ping_Call) Run(run func(ctx context.Context)) *MockTransientDatabase_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_Ping_Call) Return(err error) *MockTransientDatabase_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransientDatabase_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockTransientDatabase_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransientDatabase_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTransientDatabase_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockTransientDatabase_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockTransientDatabase_Set_Call {
	return &MockTransientDatabase_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockTransientDatabase_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockTransientDatabase_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_Set_Call) Return(err error) *MockTransientDatabase_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransientDatabase_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockTransientDatabase_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpiration provides a mock function for the type MockTransientDatabase
func (_mock *MockTransientDatabase) SetWithExpiration(ctx context.Context, key string, value string, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransientDatabase_SetWithExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpiration'
type MockTransientDatabase_SetWithExpiration_Call struct {
	*mock.Call
}

// SetWithExpiration is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - expiration time.Duration
func (_e *MockTransientDatabase_Expecter) SetWithExpiration(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockTransientDatabase_SetWithExpiration_Call {
	return &MockTransientDatabase_SetWithExpiration_Call{Call: _e.mock.On("SetWithExpiration", ctx, key, value, expiration)}
}

func (_c *MockTransientDatabase_SetWithExpiration_Call) Run(run func(ctx context.Context, key string, value string, expiration time.Duration)) *MockTransientDatabase_SetWithExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransientDatabase_SetWithExpiration_Call) Return(err error) *MockTransientDatabase_SetWithExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransientDatabase_SetWithExpiration_Call) RunAndReturn(run func(ctx context.Context, key string, value string, expiration time.Duration) error) *MockTransientDatabase_SetWithExpiration_Call {
	_c.Call.Return(run)
	return _c
}
